/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Redefined color tokens mapping to CSS variables for dynamic themes
        cyber: {
          bg: 'var(--color-bg)',
          surface: 'var(--color-surface)',
          panel: 'var(--color-panel)',
          border: 'var(--color-border)',
          muted: 'var(--color-muted)',
          text: 'var(--color-text)',
        },
        accent: {
          DEFAULT: 'var(--color-accent)',
          dark: 'var(--color-accent-dark)',
          glow: 'var(--color-accent-glow)',
          dim: 'var(--color-accent-dark)',
        },
        // DeutschMastery semantic tokens (CSS-variable-backed, theme-aware)
        dm: {
          primary: 'var(--dm-primary)',
          'on-primary': 'var(--dm-on-primary)',
          surface: 'var(--dm-surface)',
          'on-surface': 'var(--dm-on-surface)',
          'on-surface-variant': 'var(--dm-on-surface-variant)',
          'surface-low': 'var(--dm-surface-container-low)',
          'surface-container': 'var(--dm-surface-container)',
          'surface-high': 'var(--dm-surface-container-high)',
          border: 'var(--dm-outline-variant)',
          background: 'var(--dm-background)',
          error: 'var(--dm-error)',
        },
        // Google Stitch component colors
        primary: "#004ac6",
        "secondary-fixed-dim": "#eec200",
        "on-secondary-fixed-variant": "#574500",
        "on-surface-variant": "#434655",
        "outline-variant": "#c3c6d7",
        "on-surface": "#191b23",
        "on-secondary-fixed": "#231b00",
        "inverse-primary": "#b4c5ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e7e7f3",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#f0f0fb",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#4ae176",
        "on-primary-fixed-variant": "#003ea8",
        "on-tertiary-fixed-variant": "#005321",
        "secondary-fixed": "#ffe083",
        "on-tertiary-fixed": "#002109",
        "primary-fixed-dim": "#b4c5ff",
        "inverse-surface": "#2e3039",
        "tertiary-fixed": "#6bff8f",
        "on-primary-container": "#eeefff",
        "surface-container-highest": "#e1e2ed",
        "tertiary-container": "#007e37",
        error: "#ba1a1a",
        "surface-tint": "#0053db",
        "surface-dim": "#d9d9e5",
        "on-secondary": "#ffffff",
        "primary-container": "#2563eb",
        "secondary-container": "#fed01b",
        "surface-variant": "#e1e2ed",
        "primary-fixed": "#dbe1ff",
        "on-primary": "#ffffff",
        "surface-container-low": "#f3f3fe",
        outline: "#737686",
        "on-background": "#191b23",
        "on-tertiary-container": "#c1ffc5",
        background: "#faf8ff",
        "on-primary-fixed": "#00174b",
        "surface-bright": "#faf8ff",
        surface: "#faf8ff",
        tertiary: "#006229",
        "on-secondary-container": "#6f5900",
        secondary: "#735c00",
        "on-error": "#ffffff",
        "surface-container": "#ededf9"
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'Segoe UI', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'Consolas', 'monospace'],
        display: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
      },
      boxShadow: {
        glow: 'var(--shadow-glow)',
        panel: 'var(--shadow-panel)',
        premium: '0 4px 20px -2px rgba(99, 102, 241, 0.08), 0 2px 6px -1px rgba(0, 0, 0, 0.04)',
      },
      backgroundImage: {
        'grid-glow':
          'linear-gradient(var(--bg-grid-color) 1px, transparent 1px), linear-gradient(90deg, var(--bg-grid-color) 1px, transparent 1px)',
      },
      backgroundSize: {
        grid: '32px 32px',
      },
      spacing: {
        "margin-mobile": "16px",
        "stack-sm": "8px",
        gutter: "24px",
        "margin-desktop": "32px",
        unit: "4px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "container-max": "1200px"
      },
      fontSize: {
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "1.4", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "label-sm": ["12px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
};
