"""add_vocab_metadata

Revision ID: 1ed0f709884e
Revises: 3c2ff6c040ca
Create Date: 2026-07-28 09:20:16.298540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '1ed0f709884e'
down_revision: Union[str, None] = '3c2ff6c040ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vocabulary', sa.Column('part_of_speech', sa.String(length=50), nullable=True))
    op.add_column('vocabulary', sa.Column('infinitive', sa.String(length=200), nullable=True))
    op.add_column('vocabulary', sa.Column('lesson_id', sa.Integer(), nullable=True))
    op.add_column('vocabulary', sa.Column('grammar_topic', sa.String(length=100), nullable=True))
    op.add_column('vocabulary', sa.Column('difficulty', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vocabulary', 'difficulty')
    op.drop_column('vocabulary', 'grammar_topic')
    op.drop_column('vocabulary', 'lesson_id')
    op.drop_column('vocabulary', 'infinitive')
    op.drop_column('vocabulary', 'part_of_speech')
    # ### end Alembic commands ###
