"""Initial schema

Revision ID: 33647eecb9ab
Revises:
Create Date: 2026-07-25 12:47:17.355084

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '33647eecb9ab'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_message_id'), 'chat_message', ['id'], unique=False)
    op.create_table('grammar_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('lesson', sa.String(length=50), nullable=False),
    sa.Column('explanation_uz', sa.Text(), nullable=False),
    sa.Column('explanation_en', sa.Text(), nullable=False),
    sa.Column('examples_json', sa.JSON(), nullable=False),
    sa.Column('common_mistakes_json', sa.JSON(), nullable=False),
    sa.Column('practice_questions_json', sa.JSON(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grammar_topic_id'), 'grammar_topic', ['id'], unique=False)
    op.create_table('homework_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('corrections_json', sa.JSON(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homework_submission_id'), 'homework_submission', ['id'], unique=False)
    op.create_table('mistake_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('incorrect_text', sa.Text(), nullable=False),
    sa.Column('corrected_text', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('lesson', sa.String(length=50), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mistake_log_category'), 'mistake_log', ['category'], unique=False)
    op.create_index(op.f('ix_mistake_log_id'), 'mistake_log', ['id'], unique=False)
    op.create_table('user_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_course', sa.String(length=100), nullable=False),
    sa.Column('current_lesson', sa.Integer(), nullable=False),
    sa.Column('study_streak', sa.Integer(), nullable=False),
    sa.Column('last_study_date', sa.Date(), nullable=True),
    sa.Column('weekly_goal_hours', sa.Float(), nullable=False),
    sa.Column('target_level', sa.String(length=10), nullable=False),
    sa.Column('reading_level', sa.String(length=10), nullable=False),
    sa.Column('listening_level', sa.String(length=10), nullable=False),
    sa.Column('writing_level', sa.String(length=10), nullable=False),
    sa.Column('speaking_level', sa.String(length=10), nullable=False),
    sa.Column('grammar_level', sa.String(length=10), nullable=False),
    sa.Column('vocabulary_level', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_progress_id'), 'user_progress', ['id'], unique=False)
    op.create_table('vocabulary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('german', sa.String(length=200), nullable=False),
    sa.Column('translation', sa.String(length=200), nullable=False),
    sa.Column('example_sentence', sa.Text(), nullable=False),
    sa.Column('cefr_level', sa.String(length=10), nullable=False),
    sa.Column('lesson', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('box', sa.Integer(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('next_review', sa.Date(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('times_reviewed', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocabulary_german'), 'vocabulary', ['german'], unique=False)
    op.create_index(op.f('ix_vocabulary_id'), 'vocabulary', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vocabulary_id'), table_name='vocabulary')
    op.drop_index(op.f('ix_vocabulary_german'), table_name='vocabulary')
    op.drop_table('vocabulary')
    op.drop_index(op.f('ix_user_progress_id'), table_name='user_progress')
    op.drop_table('user_progress')
    op.drop_index(op.f('ix_mistake_log_id'), table_name='mistake_log')
    op.drop_index(op.f('ix_mistake_log_category'), table_name='mistake_log')
    op.drop_table('mistake_log')
    op.drop_index(op.f('ix_homework_submission_id'), table_name='homework_submission')
    op.drop_table('homework_submission')
    op.drop_index(op.f('ix_grammar_topic_id'), table_name='grammar_topic')
    op.drop_table('grammar_topic')
    op.drop_index(op.f('ix_chat_message_id'), table_name='chat_message')
    op.drop_table('chat_message')
    # ### end Alembic commands ###
