"""add exercises_json to curriculum_lesson

Revision ID: 3c2ff6c040ca
Revises: 6c45ec8b35c4
Create Date: 2026-07-27 17:51:04.579678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '3c2ff6c040ca'
down_revision: Union[str, None] = '6c45ec8b35c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curriculum_lesson', sa.Column('exercises_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('curriculum_lesson', 'exercises_json')
    # ### end Alembic commands ###
