"""add_user_progress_extended_fields

Revision ID: 6c45ec8b35c4
Revises: 3687e58025db
Create Date: 2026-07-27 17:39:50.114865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c45ec8b35c4'
down_revision: Union[str, None] = '3687e58025db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_progress', sa.Column('completed_lessons', sa.JSON(), nullable=True))
    op.add_column('user_progress', sa.Column('lesson_progress', sa.JSON(), nullable=True))
    op.add_column('user_progress', sa.Column('completed_grammar_topics', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_progress', 'completed_grammar_topics')
    op.drop_column('user_progress', 'lesson_progress')
    op.drop_column('user_progress', 'completed_lessons')
    # ### end Alembic commands ###
